#r "System"
#r "System.Core"
#r "System.Drawing"
#r "System.Numerics"
#r @".\..\..\BinPrebuilt\Release\Aardvark.Base.TypeProviders.dll"
#r @".\..\..\Bin\Debug\Aardvark.Base.FSharp.dll"
#r @".\..\..\Bin\Debug\Aardvark.Base.dll"
