namespace FShade.GLSL

module GLSLExtension =
    let [<Literal>] AMDGpuShaderHalfFloat                   = "GL_AMD_gpu_shader_half_float"
    let [<Literal>] AMDGpuShaderInt16                       = "GL_AMD_gpu_shader_int16"
    let [<Literal>] AMDGpuShaderInt64                       = "GL_AMD_gpu_shader_int64"
    let [<Literal>] ARBGpuShaderFp64                        = "GL_ARB_gpu_shader_fp64"
    let [<Literal>] ARBGpuShaderInt64                       = "GL_ARB_gpu_shader_int64"
    let [<Literal>] ARBSeparateShaderObjects                = "GL_ARB_separate_shader_objects"
    let [<Literal>] ARBShaderTextureImageSamples            = "GL_ARB_shader_texture_image_samples"
    let [<Literal>] ARBShadingLanguage420pack               = "GL_ARB_shading_language_420pack"
    let [<Literal>] ARBTessellationShader                   = "GL_ARB_tessellation_shader"
    let [<Literal>] EXTDebugPrintf                          = "GL_EXT_debug_printf"
    let [<Literal>] EXTRayTracing                           = "GL_EXT_ray_tracing"
    let [<Literal>] EXTRayTracingPositionFetch              = "GL_EXT_ray_tracing_position_fetch"
    let [<Literal>] EXTShader16bitStorage                   = "GL_EXT_shader_16bit_storage"
    let [<Literal>] EXTShader8bitStorage                    = "GL_EXT_shader_8bit_storage"
    let [<Literal>] EXTShaderExplicitArithmeticTypesFloat16 = "GL_EXT_shader_explicit_arithmetic_types_float16"
    let [<Literal>] EXTShaderExplicitArithmeticTypesFloat64 = "GL_EXT_shader_explicit_arithmetic_types_float64"
    let [<Literal>] EXTShaderExplicitArithmeticTypesInt8    = "GL_EXT_shader_explicit_arithmetic_types_int8"
    let [<Literal>] EXTShaderExplicitArithmeticTypesInt16   = "GL_EXT_shader_explicit_arithmetic_types_int16"
    let [<Literal>] EXTShaderExplicitArithmeticTypesInt64   = "GL_EXT_shader_explicit_arithmetic_types_int64"
    let [<Literal>] NVGpuShader5                            = "GL_NV_gpu_shader5"
    let [<Literal>] NVShaderInvocationReorder               = "GL_NV_shader_invocation_reorder"