<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FShade.Aot.Tests.Shaders</RootNamespace>
    <AssemblyName>FShade.Aot.Tests.Shaders</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Shaders.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Libs\FShade.Core\FShade.Core.fsproj" />
  </ItemGroup>
</Project>
