name: Publish
on:
  push:
    branches:
      - master
    paths:
      - RELEASE_NOTES.md
      - .github/workflows/publish.yml
jobs:
  pack:
    name: Package
    runs-on: windows-latest
    permissions:
      id-token: write # enable GitHub OIDC token issuance for this job
      contents: write
      packages: write
    steps:  
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Pack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .\pack.cmd

      - name: Test
        run: dotnet test src\FShade.sln -c Release --no-build --nologo --logger:"console;verbosity=normal"

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: bin\pack

      - name: GitHub Packages
        env:
          NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: dotnet nuget push "bin\pack\*.nupkg" -k %NUGET_KEY% -s "https://nuget.pkg.github.com/krauthaufen/index.json" --skip-duplicate

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: NuGet
        shell: cmd
        run: dotnet nuget push "bin\pack\*.nupkg" -k ${{steps.login.outputs.NUGET_API_KEY}} -s "https://api.nuget.org/v3/index.json" --skip-duplicate
